# Generated by Django 4.0.3 on 2022-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='profile_image2.jpg', null=True, upload_to=''),
        ),
    ]
